// ------------------------------------------------------------------------------
//  <auto-generated>
//      This code was generated by SpecFlow (https://www.specflow.org/).
//      SpecFlow Version:3.9.0.0
//      SpecFlow Generator Version:3.9.0.0
// 
//      Changes to this file may cause incorrect behavior and will be lost if
//      the code is regenerated.
//  </auto-generated>
// ------------------------------------------------------------------------------
#region Designer generated code
#pragma warning disable
namespace Fernweh.UITests._Features.ThePublicLibrary.BookDetail
{
    using TechTalk.SpecFlow;
    using System;
    using System.Linq;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [Xunit.TraitAttribute("Category", "smoke")]
    [Xunit.TraitAttribute("Category", "thepubliclibrary")]
    [Xunit.TraitAttribute("Category", "book")]
    [Xunit.TraitAttribute("Category", "bookdetail")]
    public partial class BookDetailExperienceFeature : object, Xunit.IClassFixture<BookDetailExperienceFeature.FixtureData>, System.IDisposable
    {
        
        private static TechTalk.SpecFlow.ITestRunner testRunner;
        
        private static string[] featureTags = new string[] {
                "smoke",
                "thepubliclibrary",
                "book",
                "bookdetail"};
        
        private Xunit.Abstractions.ITestOutputHelper _testOutputHelper;
        
#line 1 "BookDetail.Feature"
#line hidden
        
        public BookDetailExperienceFeature(BookDetailExperienceFeature.FixtureData fixtureData, Fernweh_UITests_XUnitAssemblyFixture assemblyFixture, Xunit.Abstractions.ITestOutputHelper testOutputHelper)
        {
            this._testOutputHelper = testOutputHelper;
            this.TestInitialize();
        }
        
        public static void FeatureSetup()
        {
            testRunner = TechTalk.SpecFlow.TestRunnerManager.GetTestRunner();
            TechTalk.SpecFlow.FeatureInfo featureInfo = new TechTalk.SpecFlow.FeatureInfo(new System.Globalization.CultureInfo("en-US"), "_Features/ThePublicLibrary/BookDetail", "Book Detail Experience", "    As a guest user\r\n    I want to be able to see the books detail\r\n    So that I" +
                    " can find out more about the book", ProgrammingLanguage.CSharp, featureTags);
            testRunner.OnFeatureStart(featureInfo);
        }
        
        public static void FeatureTearDown()
        {
            testRunner.OnFeatureEnd();
            testRunner = null;
        }
        
        public void TestInitialize()
        {
        }
        
        public void TestTearDown()
        {
            testRunner.OnScenarioEnd();
        }
        
        public void ScenarioInitialize(TechTalk.SpecFlow.ScenarioInfo scenarioInfo)
        {
            testRunner.OnScenarioInitialize(scenarioInfo);
            testRunner.ScenarioContext.ScenarioContainer.RegisterInstanceAs<Xunit.Abstractions.ITestOutputHelper>(_testOutputHelper);
        }
        
        public void ScenarioStart()
        {
            testRunner.OnScenarioStart();
        }
        
        public void ScenarioCleanup()
        {
            testRunner.CollectScenarioErrors();
        }
        
        void System.IDisposable.Dispose()
        {
            this.TestTearDown();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="I see the book details using inline table data with a little more focus on pageob" +
            "jectmodel helping providing quality check logic")]
        [Xunit.TraitAttribute("FeatureTitle", "Book Detail Experience")]
        [Xunit.TraitAttribute("Description", "I see the book details using inline table data with a little more focus on pageob" +
            "jectmodel helping providing quality check logic")]
        [Xunit.InlineDataAttribute("978-0-00-000000-6", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-7", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-8", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-9", new string[0])]
        public void ISeeTheBookDetailsUsingInlineTableDataWithALittleMoreFocusOnPageobjectmodelHelpingProvidingQualityCheckLogic(string isbn, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("isbn", isbn);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I see the book details using inline table data with a little more focus on pageob" +
                    "jectmodel helping providing quality check logic", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 7
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 8
        testRunner.Given(string.Format("I navigate to book by isbn \"{0}\"", isbn), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 9
        testRunner.Then(string.Format("I see the book details for \"{0}\"", isbn), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [Xunit.SkippableTheoryAttribute(DisplayName="I see the book details using inline table data with assertions in step bindings p" +
            "roviding quality check logic")]
        [Xunit.TraitAttribute("FeatureTitle", "Book Detail Experience")]
        [Xunit.TraitAttribute("Description", "I see the book details using inline table data with assertions in step bindings p" +
            "roviding quality check logic")]
        [Xunit.InlineDataAttribute("978-0-00-000000-6", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-7", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-8", new string[0])]
        [Xunit.InlineDataAttribute("978-0-00-000000-9", new string[0])]
        public void ISeeTheBookDetailsUsingInlineTableDataWithAssertionsInStepBindingsProvidingQualityCheckLogic(string isbn, string[] exampleTags)
        {
            string[] tagsOfScenario = exampleTags;
            System.Collections.Specialized.OrderedDictionary argumentsOfScenario = new System.Collections.Specialized.OrderedDictionary();
            argumentsOfScenario.Add("isbn", isbn);
            TechTalk.SpecFlow.ScenarioInfo scenarioInfo = new TechTalk.SpecFlow.ScenarioInfo("I see the book details using inline table data with assertions in step bindings p" +
                    "roviding quality check logic", null, tagsOfScenario, argumentsOfScenario, featureTags);
#line 17
    this.ScenarioInitialize(scenarioInfo);
#line hidden
            if ((TagHelper.ContainsIgnoreTag(tagsOfScenario) || TagHelper.ContainsIgnoreTag(featureTags)))
            {
                testRunner.SkipScenario();
            }
            else
            {
                this.ScenarioStart();
#line 18
        testRunner.Given(string.Format("I navigate to book by isbn \"{0}\"", isbn), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Given ");
#line hidden
#line 19
        testRunner.Then(string.Format("I see the book details with feature file providing quality check logic \"{0}\"", isbn), ((string)(null)), ((TechTalk.SpecFlow.Table)(null)), "Then ");
#line hidden
            }
            this.ScenarioCleanup();
        }
        
        [System.CodeDom.Compiler.GeneratedCodeAttribute("TechTalk.SpecFlow", "3.9.0.0")]
        [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
        public class FixtureData : System.IDisposable
        {
            
            public FixtureData()
            {
                BookDetailExperienceFeature.FeatureSetup();
            }
            
            void System.IDisposable.Dispose()
            {
                BookDetailExperienceFeature.FeatureTearDown();
            }
        }
    }
}
#pragma warning restore
#endregion
